/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package affichage;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import affichage.Passerelle;
import java.time.LocalDate;
import java.time.LocalTime;
/**
 *
 * @author sio2021
 */
public class authentification extends javax.swing.JFrame {

    private static Patient unPatient;
    /**
     * Creates new form authentification
     */
    public authentification() {
        initComponents();
        Passerelle.Connexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JButton();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblMdp = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        txtMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitre.setText("Authentification");

        btnQuitter.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        lblNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNom.setText("Service : ");

        txtNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblMdp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMdp.setText("Mot de passe :");

        btnValider.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnValider)
                        .addGap(284, 284, 284))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnValider)
                .addGap(71, 71, 71)
                .addComponent(btnQuitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        String nom = txtNom.getText();
        String mdp = txtMdp.getText();
        JFrame fenetre = new JFrame();
        
        if(!nom.isEmpty()){
            if(!mdp.isEmpty()){
                try{
                    if(PersonnelDAO.verifUtilisateur(nom,mdp)){
                        Service unService = new Service(ServiceDAO.getIdService(nom),ServiceDAO.getService(ServiceDAO.getIdService(nom)));
                        Historique unHisto = new Historique(ServiceDAO.getIdService(nom), LocalDate.now(), LocalTime.now());
                        HistoriqueDAO dao = new HistoriqueDAO();
                        dao.create(unHisto);
                        if(unService.getId() == 14){
                            JDAdmin f = new JDAdmin(this, true);
                            this.setVisible(false);
                            f.setVisible(true);
                        }
                        else{
                            Acceuil f = new Acceuil(this, true, unService, unPatient);
                            this.setVisible(false);
                            f.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(fenetre,"Identifiant ou mot de passe invalide.");
                    }
                }
                catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            else{
                JOptionPane.showMessageDialog(fenetre,"Saisir un mot de passe valide.");
            }
        }
        else{
            JOptionPane.showMessageDialog(fenetre,"Saisir un nom valide.");
        }
        
    }//GEN-LAST:event_btnValiderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel lblMdp;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPasswordField txtMdp;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
