package affichage;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Seïf-Eddin
 */
public class JDAjoutCommand extends javax.swing.JDialog {

    private static Service unService;
    Frame leParent;

    /**
     * Creates new form JDAjoutCommand
     */
    public JDAjoutCommand(java.awt.Frame parent, boolean modal, Service leService) {
        super(parent, modal);
        initComponents();
        unService = leService;
        DefaultListModel listModel = new DefaultListModel();

        for (Patient pat : PatientDAO.donnerTousLesPatientsParS(unService.getId())) {
            listModel.addElement(pat);
        }
        lstPatient.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAjout = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPatient = new javax.swing.JList<>();
        btnDeco = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 550));

        lblAjout.setBackground(new java.awt.Color(255, 255, 255));
        lblAjout.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblAjout.setForeground(new java.awt.Color(153, 0, 0));
        lblAjout.setText("Ajouter les repas");

        btnValider.setBackground(new java.awt.Color(0, 153, 0));
        btnValider.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnValider.setForeground(new java.awt.Color(0, 0, 0));
        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        lstPatient.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lstPatient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPatientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstPatient);

        btnDeco.setBackground(new java.awt.Color(204, 102, 0));
        btnDeco.setForeground(new java.awt.Color(0, 0, 0));
        btnDeco.setText("Déconnexion");
        btnDeco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 270, Short.MAX_VALUE)
                .addComponent(lblAjout)
                .addGap(235, 235, 235))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAjout)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPatientMouseClicked
        int choix = lstPatient.getSelectedIndex();
        Object val = lstPatient.getModel().getElementAt(choix);
        Patient unPat = (Patient) val;
        JDType laJDType = new JDType(leParent, true, unPat, this, unService);
        laJDType.setVisible(true);
    }//GEN-LAST:event_lstPatientMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnValiderMouseClicked

    private void btnDecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecoMouseClicked
        this.setVisible(false);
        authentification f = new authentification();
        f.setVisible(true);
    }//GEN-LAST:event_btnDecoMouseClicked

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAjoutCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAjoutCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAjoutCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAjoutCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAjoutCommand dialog = new JDAjoutCommand(new javax.swing.JFrame(), true, unService);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeco;
    private javax.swing.JButton btnValider;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAjout;
    private javax.swing.JList<String> lstPatient;
    // End of variables declaration//GEN-END:variables
}
